platform :ios, '9.0'

target 'ReactNativeWithSendBird' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReactNativeWithSendBird
  pod 'Firebase/Core', '~> 6.1.0'
  pod 'Firebase/Messaging', '~> 6.1.0'

  target 'ReactNativeWithSendBird-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'


    pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

    pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  end

  target 'ReactNativeWithSendBirdTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
