# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ReactNativeWithSendBird' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Firebase/Core', '~> 5.20.1'
  pod 'Firebase/Messaging', '~> 5.20.1'

end
