# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactNativeWithSendBird' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactNativeWithSendBird
  pod 'Firebase/Messaging'

  target 'ReactNativeWithSendBirdTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ReactNativeWithSendBird-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactNativeWithSendBird-tvOS

  target 'ReactNativeWithSendBird-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
